name: Build

on: 
  push:
    branches: master
    paths-ignore: '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
        DOTNET_USE_SHORT_FIRST_RUN_MESSAGE: 0
        DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1
    - run: dotnet publish -c Release -o out
    - uses: actions/upload-artifact@v1
      with:
        name: Emby.Plugins.AnimeKai
        path: out/Emby.Plugins.AnimeKai.dll
