name: Publish Plugin

on: 
  push:
    branches: master
    paths-ignore: '**.md'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
    - run: dotnet publish -c Release -o out
    - uses: actions/upload-artifact@v1
      with:
        name: Emby.Plugins.AnimeKai
        path: out/Emby.Plugins.AnimeKai.dll
